[build]
    build = "npm install"
    functions = "./functions"
    GIT_LFS_ENABLED = true
    publish = "public/"
[[redirects]]
    from = "/api/v1/:splat"
    to = "/.netlify/functions/:splat"
    status = 200